memory: 500M
disk_quota: 500M
toolbox_cookie_session_encryption_secret: asdjhbwefbo23r23rbfik2roiwhefwbqw
toolbox_sentry_dsn: https://fakesentrydsn@example.com/12
toolbox_auth_github_team_id: 123
toolbox_auth_github_admin_team_id: 123
toolbox_auth_github_client_id: asdjhbwefbo23r23rbfik2roiwhefwbqw
toolbox_auth_github_client_secret: asdjhbwefbo23r23rbfik2roiwhefwbqw
toolbox_stripe_account_api_key: asdjhbwefbo23r23rbfik2roiwhefwbqw
toolbox_auth_github_enabled: true
toolbox_disable_request_logging: true
